Built Navbar, HeroSection, EventsCard, ServiceCard, Footer, 404 Page
csss-uofr/website pull request #1
Opened 2024-07-28 09:41 UTC by WeSecureYou

I've built the following things mentioned in the title so far and currently building the rest of the things, expect it to be done within a week :))

2024-07-28 09:44 UTC, WeSecureYou commented
Review it and let me know if any changes is required. If you want to see live demo of the work i have hosted it for temporary basis here: [Live Demo](https://websitecss.vercel.app/)

2024-08-15 21:26 UTC, kpatel0170 commented on src/components/EC.jsx
Event's card doesn't show appropriate information, 
- date, time and location

2024-08-15 21:28 UTC, kpatel0170 commented on src/components/EventsCard.jsx
The data can be in separate file or maybe dynamic based on event name:

example: github-event.json or react-event.json

2024-08-15 21:30 UTC, kpatel0170 commented on src/components/ServiceSection.jsx
separate data format

2024-08-15 21:32 UTC, kpatel0170 commented on src/pages/Elections.jsx
elections are yearly so maybe with 2024.json or 2024.md

2024-08-15 21:36 UTC, kpatel0170 requested changes
- [x] separate static data (/data/...) - .md format or .json format
- [x] load data dynamically based on data files
- [x] add code of conduct page from https://github.com/csss-uofr/code-of-conduct
- [ ] add constitution page 
- [x] update colors best suited based on current logo

2024-08-19 17:39 UTC, WeSecureYou commented
Noted. I just need the current UR CSSS logo in the best quality possible. Thanks!

2024-08-27 06:28 UTC, WeSecureYou commented
All of the above-mentioned changes have been taken care of. Please take a look at the [Live Demo](https://websitecss.vercel.app/) and let me know if anything further is required

2024-08-27 06:36 UTC, WeSecureYou commented
Please note that the data in the JSON files is dummy data since I don't have access to the actual data. The About Us page might need some editing because I don't have the actual content that needs to be included on that page. The menu button on mobile devices still needs to be implemented (You can expect it to be done in the next few commits). Also, I'm not really sure what you meant by the 'Constitution Page'.

2024-10-05 17:03 UTC, kpatel0170 approved these changes
LGTM :)

2024-10-05 17:09 UTC, merged